import sympy
# print("输入你的姓名和密码")
# print("Your name:")
# name = input()
# print("Your email")
# email = input()
# print("name:"+name)
# print("email:"+email)
c = sympy.Abs(-8)+sympy.sqrt(9)
print(c)
